name: "[EN] Bug report"
description: "Report a bug or unexpected behavior"
title: "[BUG] "
labels: [bug]
body:
  - type: textarea
    attributes:
      label: Description
      description: "Describe the bug"
    validations:
      required: true

  - type: input
    attributes:
      label: Jeedom Version
      placeholder: "ex: 4.4.0"

  - type: textarea
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. ...
        2. ...
        3. ...

  - type: textarea
    attributes:
      label: Logs
      description: "Add logs if available"
