name: "Rapport de bug / Bug report"
description: "Signalez un comportement inattendu ou un problème / Report an unexpected behavior or a problem"
title: "[BUG] "
labels: [bug]
body:
  - type: textarea
    attributes:
      label: Description
      description: "Décrivez le problème / Describe the bug"
    validations:
      required: true

  - type: dropdown
    id: hardware-version
    attributes:
      label: Type de matériel / Hardware type
      description: "Sélectionnez le type de matériel concerné / Select the affected hardware type"
      options:
        - "Jeedom Smart"
        - "Jeedom Atlas"
        - "Jeedom Luna"
        - "VM"
        - "Raspberry Pi"
        - "Docker"
        - "Autre / Other"
    validations:
      required: true


  - type: input
    attributes:
      label: Version de Jeedom / Jeedom Version
      placeholder: "ex: 4.4.0"
    validations:
      required: true

  - type: input
    attributes:
      label: Version du plugin/composant / Plugin or component version
      placeholder: "ex: 1.2.3"
    validations:
      required: false

  - type: input
    attributes:
      label: Environnement (navigateur, OS, etc.) / Environment (browser, OS, etc.)
      placeholder: "ex: Chrome 123, Windows 11"
    validations:
      required: false

  - type: textarea
    attributes:
      label: Étapes pour reproduire / Steps to reproduce
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Logs
      description: "Ajoutez les logs si disponibles / Add logs if available"
    validations:
      required: false