name: "[FR] Rapport de bug"
description: "Signalez un comportement inattendu ou un problème"
title: "[BUG] "
labels: [bug]
body:
  - type: textarea
    attributes:
      label: Description
      description: "Décrivez le problème"
    validations:
      required: true

  - type: input
    attributes:
      label: Version de Jeedom
      placeholder: "ex: 4.4.0"

  - type: textarea
    attributes:
      label: Étapes pour reproduire
      placeholder: |
        1. ...
        2. ...
        3. ...

  - type: textarea
    attributes:
      label: Logs
      description: "Ajoutez les logs si disponibles"
