name: "🌍 Choisir une langue / Choose a language / Elegir idioma"
description: "Créer un ticket dans la langue de votre choix / Create an issue in your language"
body:
  - type: markdown
    attributes:
      value: |
        ### 🇫🇷 Français  
        👉 [Créer un rapport de bug](https://github.com/TON_REPO/issues/new?template=bug_report_fr.yml)  
        👉 [Proposer une amélioration](https://github.com/TON_REPO/issues/new?template=feature_request_fr.yml)

        ### 🇬🇧 English  
        👉 [Create a bug report](https://github.com/TON_REPO/issues/new?template=bug_report_en.yml)  
        👉 [Suggest a feature](https://github.com/TON_REPO/issues/new?template=feature_request_en.yml)

        ### 🇪🇸 Español  
        👉 [Informar un error](https://github.com/TON_REPO/issues/new?template=bug_report_esp.yml)  
        👉 [Solicitar una mejora](https://github.com/TON_REPO/issues/new?template=feature_request_esp.yml)
