name: "[EN] Feature request"
description: "Suggest an idea or enhancement"
title: "[FEATURE] "
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: Description
      description: "Describe your idea"

  - type: textarea
    attributes:
      label: Use case
      description: "What is the need ?"

  - type: checkboxes
    attributes:
      label: Portée
      options:
        - label: Core 
        - label: Offical plugin
        - label: Third-party plugin
