name: "[FR] Proposition d'amélioration"
description: "Suggérez une idée ou une fonctionnalité"
title: "[FEATURE] "
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: Description
      description: "Décrivez votre idée"

  - type: textarea
    attributes:
      label: Cas d’usage / Use case
      description: "Quel est le besoin ?"

  - type: checkboxes
    attributes:
      label: Portée
      options:
        - label: Core
        - label: Plugin officiel
        - label: Plugin communautaire
