name: [ESP] Solicitud de función
description: Sugiera una idea o función
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: Description
      description: Describe your idea / Décrivez votre idée / Describa su idea

  - type: textarea
    attributes:
      label: Use Case
      description: How would this improve the experience? / En quoi cela améliore-t-il l'expérience ? / ¿Cómo mejoraría esto la experiencia?

  - type: textarea
    attributes:
      label: Screenshots or Mockups
      description: Optional visuals / Visuels facultatifs / Visuales opcionales

  - type: checkboxes
    attributes:
      label: This request concerns / Cette demande concerne / Esta solicitud se refiere a:
      options:
        - label: Core / Coeur / Núcleo
        - label: Official plugin / Plugin officiel / Complemento oficial
        - label: Community plugin / Plugin communautaire / Complemento comunitario
